//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYC_REI_Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eviction
    {
        public int EvictionID { get; set; }
        public string COURT_INDEX_NUMBER { get; set; }
        public string DOCKET_NUMBER { get; set; }
        public string EVICTION_ADDRESS { get; set; }
        public string EVICTION_APT_NUM { get; set; }
        public Nullable<System.DateTime> EXECUTED_DATE { get; set; }
        public string MARSHAL_FIRST_NAME { get; set; }
        public string MARSHAL_LAST_NAME { get; set; }
        public string RESIDENTIAL_COMMERCIAL_IND { get; set; }
        public string BOROUGH { get; set; }
        public string EVICTION_ZIP { get; set; }
    }
}
