//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYC_REI_Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecFiling
    {
        public int ID { get; set; }
        public int CIK { get; set; }
        public string CompanyName { get; set; }
        public string FormType { get; set; }
        public System.DateTime DateFiled { get; set; }
        public string Filename { get; set; }
    }
}
